# Generated by Django 4.1.2 on 2022-10-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_arrive', models.TimeField(blank=True)),
                ('time_leave', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_no', models.IntegerField()),
                ('class_title', models.CharField(max_length=100)),
                ('class_date', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_description', models.CharField(max_length=100)),
                ('abstract', models.TextField()),
                ('required_textbook', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CoursesPerCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('cycle_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cycle_description', models.CharField(max_length=100)),
                ('cycle_start_date', models.DateField()),
                ('cycle_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField()),
                ('cancelled', models.BooleanField()),
                ('cancelled_reason', models.CharField(blank=True, max_length=100)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursespercycle')),
            ],
        ),
    ]
