# Generated by Django 4.1.2 on 2022-10-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollments',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students'),
        ),
        migrations.AddField(
            model_name='coursespercycle',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses'),
        ),
        migrations.AddField(
            model_name='coursespercycle',
            name='cycles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.cycle'),
        ),
        migrations.AddField(
            model_name='classes',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursespercycle'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teachers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teachers'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.classes'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.students'),
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.UniqueConstraint(models.F('students'), models.F('courses'), name='enrollments_unique_courses_students'),
        ),
        migrations.AddConstraint(
            model_name='coursespercycle',
            constraint=models.UniqueConstraint(models.F('courses'), models.F('cycles'), name='cpc_unique_courses_cycles'),
        ),
        migrations.AddConstraint(
            model_name='classes',
            constraint=models.UniqueConstraint(models.F('courses'), models.F('teachers'), name='classes_unique_courses_teachers'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(models.F('classes'), models.F('students'), name='attendance_unique_classes_students'),
        ),
    ]
