# Generated by Django 4.1.2 on 2022-11-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursepost_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepost',
            old_name='image_url',
            new_name='media_url',
        ),
    ]
