# Generated by Django 4.1.2 on 2022-10-20 07:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('assignment_number', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_date', models.DateField(default=datetime.datetime.now)),
                ('assignment_deadline', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('assignments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignments')),
            ],
        ),
    ]
