# Generated by Django 4.1.2 on 2022-11-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='phone_num',
            new_name='phone_num',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='phone_num',
            new_name='phone_num',
        ),
        migrations.AlterField(
            model_name='students',
            name='birth_date',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
