# Generated by Django 4.1.2 on 2022-11-07 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phone_number_students_phone_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='phone_num',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
